version: "3"
services:
  coinmarketcap:
    hostname: coinmarketcap
    build: coinmarketcap
    ports:
      - "8081:8081"
  cryptorank:
    hostname: crytporank
    build: cryptorank
    ports:
      - "8082:8082"
  fortris:
    hostname: fortrisapp
    build: fortrisapp
    ports:
      - "8080:8080"
  mongodb:
      hostname: mongodb
      image: mongo:latest
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass
