version: "3"
services:
  coinmarketcap:
    build: coinmarketcap
    ports:
      - "8081:8081"
  cryptorank:
    build: cryptorank
    ports:
      - "8082:8082"
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
